version: '3.8'

services: 
  web:
      build: .
      command: python manage.py runserver 0.0.0.0:5000
      volumes: 
        - .:/app
      ports:
        - "5000:5000"
      environment:
        - DJANGO_ENV=development  